[package]
name = "wenderer"
version = "0.1.0"
authors = ["feng liang <feng.liang@kaust.edu.sa>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = { version = "0.25", features = ["web-sys"] }
console_error_panic_hook = "0.1.6"
cgmath = { version = "0.18", features = ["swizzle", "mint"] }
env_logger = "0.7"
log = "0.4"
wgpu = { version = "0.10", path="/home/maple/NVME/research/wgpu/wgpu" }
console_log = "0.2.0"
wasm-bindgen-futures = "0.4.26"
web-sys = {version = "0.3.53"}
crevice = "0.6.0"
mint = "0.5.6"
futures = "0.3"
anyhow = "1.0"
bytemuck = { version = "1.5", features = ["derive"] }
rayon = "1.5.1"
half = { version = "1.7", features = ["num-traits", "bytemuck"] }

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.1"
glob = "0.3"
shaderc = "0.7"