[package]
name = "wenderer"
version = "0.1.0"
authors = ["feng liang <feng.liang@kaust.edu.sa>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = "0.25"
shaderc = "0.7"
cgmath = "0.18"
env_logger = "0.7"
log = "0.4"
wgpu = "0.7"
futures = "0.3"
