[package]
name = "wenderer"
version = "0.3.1"
authors = ["feng liang <feng.liang@kaust.edu.sa>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
winit = "0.27"
cgmath = { version = "0.18", features = ["swizzle"] }
env_logger = "0.9"
log = "0.4"
wgpu = "0.15"
crevice = { version = "0.11.0", features = ["cgmath"] }
futures = "0.3"
anyhow = "1.0"
bytemuck = { version = "1.9", features = ["derive"] }
rayon = "1.5.3"
half = { version = "2.0", features = ["num-traits", "bytemuck"] }

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.1"
glob = "0.3"
shaderc = "0.8"

[profile.release]
lto = true